require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'Ders' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    # Fix for C++ header issues
    installer.pods_project.targets.each do |target|
      # Fix for all React Native C++ pods
      if target.name.start_with?("React-") || target.name.start_with?("RCT-") ||
         target.name == "React" || target.name == "ReactCommon" ||
         target.name == "React-oscompat" || target.name == "RNReanimated" ||
         target.name == "expo-dev-launcher" || target.name == "expo-dev-menu" ||
         target.name == "ExpoModulesCore"
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) FOLLY_NO_CONFIG FOLLY_MOBILE=1 FOLLY_USE_LIBCPP=1'
          config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) "${PODS_ROOT}/RCT-Folly" "${PODS_ROOT}/boost" "${PODS_ROOT}/DoubleConversion"'
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -std=c++20'
        end
      end
    end
    
    # Suppress warnings from third-party libraries
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Suppress nullability warnings for third-party libraries
        config.build_settings['CLANG_WARN_NULLABILITY_COMPLETENESS'] = 'NO'
        config.build_settings['CLANG_WARN_NULLABLE_TO_NONNULL_CONVERSION'] = 'NO'
        
        # Suppress deprecated API warnings for third-party libraries
        config.build_settings['GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS'] = 'NO'
        config.build_settings['CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS'] = 'NO'
        
        # Suppress documentation warnings
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        
        # Suppress other common warnings
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
        
        # For specific problematic pods, add more aggressive suppression
        if ['ExpoModulesCore', 'EXConstants', 'expo-dev-launcher', 'expo-dev-menu'].include?(target.name)
          config.build_settings['WARNING_CFLAGS'] = '-Wno-nullability-completeness -Wno-deprecated-declarations'
          config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -suppress-warnings'
        end
      end
      
      # Fix build phase warnings - disable dependency analysis for problematic scripts
      target.build_phases.each do |phase|
        if phase.respond_to?(:name) && phase.name == 'Create Symlinks to Header Folders'
          phase.always_out_of_date = '1'
        end
        if phase.respond_to?(:name) && phase.name == '[CP-User] Generate updates resources for expo-updates'
          phase.always_out_of_date = '1'
        end
        if phase.respond_to?(:name) && phase.name == '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed'
          phase.always_out_of_date = '1'
        end
      end
    end
  end
end
